sudo: required
dist: trusty
group: deprecated-2017Q4

env:
  - DOCKER_COMPOSE_VERSION=1.16.1

language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master
  - develop

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "brendonmscott-github"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
      - develop

services:
  - mongodb
  - com.bscott.fitness.docker

before_install:
  - sudo rm /usr/local/bin/com.bscott.fitness.docker-compose
  - curl -L https://github.com/com.bscott.fitness.docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/com.bscott.fitness.docker-compose-`uname -s`-`uname -m` > com.bscott.fitness.docker-compose
  - chmod +x com.bscott.fitness.docker-compose
  - sudo mv com.bscott.fitness.docker-compose /usr/local/bin

script: mvn clean install -Pcodecoverage-jacoco sonar:sonar

after_script:
  - echo "<settings><servers><server><id>github</id><username>\${env.GIT_HUB_USER}</username><password>\${env.GIT_HUB_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy -e --settings ~/settings.xml
