app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey

server:
  port: ${PORT:8380}
  context-path: /v1/api

spring:
  application:
    name: fitness-tracker-service
  data:
    mongodb:
      database: fitness_tracker

logging:
    pattern:
      file: "%-5level - %replace(%msg){'[\r\n]', ''}%n"
      console: "%-5level - %replace(%msg){'[\r\n]', ''}%n"
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
