version: '2'
services:
  mongo:
    image: "mongo:3.2.12"
    ports:
      - "27017:27017"
    volumes:
      - /Users/brendonscott/Documents/mongo:/data/db

  sonar:
    image: "sonarqube:latest"
    ports:
      - "9000:9000"
      - "9092:9092"