FROM mongo:3.0

# Copy seed script and files to container. These will be used by the startup script to seed Mongo
# COPY com.bscott.fitness.docker-entrypoint-initdb.d /com.bscott.fitness.docker-entrypoint-initdb.d